# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 234ee1695c4f54eca91b6407ca72f3fe70eeff462244f1a6257dcca3ceed6e90c2622a395253fc9932dd12ef73870f64551f8895d269ebe02bc4b30c3425b11a

test:
  secret_key_base: 779a80f291298dc801c023a52b5df55d49c12857b9b0aa044a964a875fb54acc7d564634777d999a4e04d8828449cedb9421611093239fa351888645215fcce7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
